salario = float(input ())
alimento = ((salario)*0.2)
print("alimento", alimento)
pasaje = ((salario)*0.15)
print("pasaje",pasaje)
cine = ((salario)*0.1)
print("cine",cine)
libros = ((salario)*0.15)
print("libros",libros)
alquiler = ((salario)-((alimento)+(pasaje)+(cine)+(libros)))
print("alquiler",alquiler)